services:
  nginx:
    profiles:
      - production-only

  certbot:
    profiles:
      - production-only

  db:
    ports:
      - "5433:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001

  redis_sessions:
    ports:
      - "6379:6379"

  redis_results:
    ports:
      - "6380:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    ports:
      - "5555:5555"
    environment:
      MODE: DEBUG
    volumes:
      - .:/app

  server:
    ports:
      - "8000:8000"
    entrypoint: ["/app/docker-entrypoint.dev.sh"]
    environment:
      MODE: DEBUG
      SECURE_SSL_REDIRECT: "false"
    volumes: !override
      - .:/app
    depends_on:
      frontend:
        condition: service_started

  worker:
    entrypoint: ["watchmedo"]
    user: "1000:1000"
    command:
      - auto-restart
      - --directory=/app/src
      - --pattern=*.py
      - --recursive
      - --
      - celery
      - -A
      - aspire_v2
      - worker
      - -l
      - INFO
      - --concurrency=${CELERY_WORKER_CONCURRENCY:-2}
    environment:
      MODE: DEBUG
    volumes:
      - .:/app

  frontend:
    image: node:22-alpine
    working_dir: /app/src/aspire_v2/frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
    restart: unless-stopped
