# Generated by Django 5.2.6 on 2025-11-16 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='resources')),
                ('file_type', models.CharField(choices=[('QREL', 'Qrel'), ('QUERIES', 'Queries'), ('RUNS', 'Runs')], max_length=7)),
            ],
        ),
    ]
