# Generated by Django 5.2.6 on 2025-11-16 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
