# Generated by Django 5.2.6 on 2025-11-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis_type',
        ),
    ]
