# Generated by Django 5.2.6 on 2025-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_analysisresult_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
