# Generated by Django 5.2.6 on 2025-11-30 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analysisresult_analysis_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('qrels', models.FileField(upload_to='res')),
                ('topics', models.FileField(upload_to='res')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='res')),
                ('date', models.DateField(auto_now_add=True)),
                ('reports', models.ManyToManyField(related_name='retrieval_runs', to='core.report')),
                ('ir_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_runs', to='core.retrievaltask')),
            ],
        ),
    ]
