# Generated by Django 5.2.6 on 2025-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_retrievaltask_retrievalrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievaltask',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
