# Generated by Django 5.2.6 on 2025-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_retrievaltask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalrun',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='retrievalrun',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retrievaltask',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='retrievaltask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
