# Generated by Django 5.2.6 on 2025-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_retrievalrun_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
