# Generated by Django 5.2.6 on 2025-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_report_description_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalrun',
            name='file',
            field=models.FileField(upload_to='runs'),
        ),
        migrations.AlterField(
            model_name='retrievaltask',
            name='qrels',
            field=models.FileField(upload_to='qrels'),
        ),
        migrations.AlterField(
            model_name='retrievaltask',
            name='topics',
            field=models.FileField(upload_to='topics'),
        ),
    ]
