# Generated by Django 5.2.6 on 2025-12-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_retrievalrun_file_alter_retrievaltask_qrels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureValue',
            fields=[
                ('pk', models.CompositePrimaryKey('retrieval_run', 'measure_name', blank=True, editable=False, primary_key=True, serialize=False)),
                ('measure_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('retrieval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='core.retrievalrun')),
            ],
        ),
    ]
