# Generated by Django 5.2.6 on 2025-12-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_measurevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievaltask',
            name='max_relevance',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
