# Generated by Django 5.2.6 on 2025-12-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_retrievaltask_max_relevance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrievaltask',
            name='max_relevance',
        ),
    ]
