# Generated by Django 5.2.6 on 2025-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_retrievaltask_max_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
    ]
