# Generated by Django 5.2.6 on 2026-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='retrievalrun',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='retrievaltask',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
