# Generated by Django 5.2.6 on 2026-09-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_description_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['date']},
        ),
    ]
